apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
  labels:
    app: django
    tier: backend
spec:
  type: NodePort
  selector:
    app: django
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
        