apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: react
    tier: frontend
spec:
  type: NodePort
  selector:
    app: react
    tier: frontend
  ports:
  - port: 3000
    targetPort: 3000
